## ------------------------------------------------------------------------ ##
##  .Brewfile                                Nicholas Berlette, 2022-08-03  ##
## ------------------------------------------------------------------------ ##
##        https://github.com/nberlette/dotfiles/blob/main/.Brewfile         ##
## ------------------------------------------------------------------------ ##
##              MIT © Nicholas Berlette <nick@berlette.com>                 ##
## ------------------------------------------------------------------------ ##

## auto-generated by the `brew bundle dump` command after installation

tap "homebrew/bundle"
tap "homebrew/core"
tap "supabase/tap"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Collection of Linux utilities
brew "util-linux"
# Secure JS/TS runtime, written in Rust
brew "deno"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Small git utilities
brew "git-extras"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Rainbows and unicorns in your console!
brew "lolcat"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Generic syntax highlighter
brew "pygments"
# Utility that provides fast incremental file transfer
brew "rsync"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Cross-shell prompt for astronauts
brew "starship"
# Supabase CLI
brew "supabase/tap/supabase"
# Access X11 clipboards from the command-line
brew "xclip"
