image:
  file: nberlette/gitpod-enhanced

ports:
  - port: 3000-5000
    onOpen: open-preview
    visibility: private

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addLabel: true
    addBadge: true
    addCheck: true

vscode:
  extensions:
    - jock.svg
    - antfu.vite
    - silvenon.mdx
    - redhat.vscode-yaml
    - Jacano.vscode-pnpm
    - vsls-contrib.gistfs
    - timonwong.shellcheck
    - eg2.vscode-npm-script
    - github.copilot-nightly
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - naumovs.color-highlight
    - foxundermoon.shell-format
    - bradlc.vscode-tailwindcss
    - editorconfig.editorconfig
    - github.github-vscode-theme
    - ms-azuretools.vscode-docker
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
